// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'content': string;
  'content_left': string;
  'content_right': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
