// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'content': string;
  'controls': string;
  'controls__button': string;
}
export const cssExports: CssExports;
export default cssExports;
