// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'actions__button': string;
  'actions__button_negative': string;
  'actions__button_positive': string;
  'closer': string;
  'content': string;
  'styled': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
