// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'actionsFiltration': string;
  'clear': string;
  'filter': string;
  'mainFiltration': string;
  'search': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
