// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'errorText': string;
  'lifted': string;
  'line': string;
  'lineMain': string;
  'metaWrapper': string;
  'metadata': string;
  'metadata__wrapper': string;
  'styled': string;
}
export const cssExports: CssExports;
export default cssExports;
