// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'delete': string;
  'dropdownElem': string;
}
export const cssExports: CssExports;
export default cssExports;
