// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'flex': string;
  'full': string;
  'half': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
