// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actionWrapper': string;
  'flex': string;
  'full': string;
  'half': string;
  'leadHelper': string;
  'membersDeleteAction': string;
  'membersDeleteAction__wrapper': string;
  'membersEntry': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
