// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clear': string;
  'heading': string;
  'heading__content': string;
  'image': string;
  'inner': string;
  'input__file': string;
  'loaderWrapper': string;
  'text': string;
  'text__inactive': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
