// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'action': string;
  'actionsFiltration': string;
  'chevron': string;
  'chevron_rotated': string;
  'chevron_rotatedReverse': string;
  'clear': string;
  'filter': string;
  'filtrationAddon': string;
  'filtrationAddon_opened': string;
  'inner': string;
  'mainFiltration': string;
  'mainFiltration__item': string;
  'openedBlock': string;
  'openedBlock__control': string;
  'search': string;
  'wrapper': string;
  'wrapper_opened': string;
}
export const cssExports: CssExports;
export default cssExports;
