// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error': string;
  'heading': string;
  'icon': string;
  'inner': string;
  'input': string;
  'input_error': string;
  'input_password': string;
  'input_readonly': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
