// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'blue': string;
  'green': string;
  'red': string;
  'styled': string;
}
export const cssExports: CssExports;
export default cssExports;
