// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footer': string;
  'group': string;
  'half': string;
  'styled': string;
}
export const cssExports: CssExports;
export default cssExports;
