// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'styled': string;
  'styled_disabled': string;
}
export const cssExports: CssExports;
export default cssExports;
