// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  action: string;
  action__content: string;
  clear: string;
  heading: string;
  heading__content: string;
  inner: string;
  input__file: string;
  loaderWrapper: string;
  photoInner: string;
  photoInner__content: string;
  text: string;
  text__inactive: string;
  wrapper: string;
}
export const cssExports: CssExports;
export default cssExports;
