// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'adminControls': string;
  'adminControls__approve': string;
  'adminControls__reject': string;
  'controls': string;
  'controls__button': string;
  'controls__last': string;
  'group': string;
  'half': string;
  'leadField': string;
  'modalContent': string;
  'styled': string;
}
export const cssExports: CssExports;
export default cssExports;
