// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'closer': string;
  'styled': string;
  'styled_error': string;
  'styled_info': string;
}
export const cssExports: CssExports;
export default cssExports;
